### ISSUE TITLE
Binaries for SDL2_image, SDL2_mixer, SDL2_ttf and SDL2_gfx

### ISSUE THREAD

**Issue by lawrence-laz** [ppy/SDL2-CS#135]
I see that there are native binaries provided for core SDL2 for all platforms, but not for additional libraries.

Are/were there any plans to include these as well?

**Comment by peppy** [comment]
We are only building the pieces we're using for our own purposes for now. I think adding those extras may add quite a bit of overhead in the release process (which we try to keep as lean as possible due to this being a two level deep dependency). If you want to get things building, you should be able to use the existing github actions scripts as a starting point.

I don't think we'll be adding these to our chain unless we start to use them ourselves, though.

**Comment by lawrence-laz** [comment]
Fair enough, thanks
